//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cavity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cavity()
        {
            this.InspectionItems = new HashSet<InspectionItem>();
        }
    
        public int CavityID { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
        public int Version { get; set; }
        public int InspectionID { get; set; }
    
        public virtual Inspection Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionItem> InspectionItems { get; set; }
    }
}
