//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checkpoint()
        {
            this.InspectionItems = new HashSet<InspectionItem>();
        }
    
        public int CheckpointId { get; set; }
        public int Part_ID { get; set; }
        public string Code { get; set; }
        public string InspectionPart { get; set; }
        public bool IsActive { get; set; }
        public bool IsMeasurement { get; set; }
        public Nullable<double> LimitLower { get; set; }
        public Nullable<double> LimitUpper { get; set; }
        public string Note { get; set; }
        public string SamplingMethod { get; set; }
        public string Specification { get; set; }
        public string Tools { get; set; }
    
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionItem> InspectionItems { get; set; }
    }
}
