//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
        }
    
        public int DeliveryID { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string DRNumber { get; set; }
        public int PriorityLevel { get; set; }
        public int Quantity { get; set; }
        public byte Urgent { get; set; }
        public int VERSION { get; set; }
        public int PartID { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
    }
}
