//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int DeliveryDetailID { get; set; }
        public string LotNumber { get; set; }
        public int LotQuantity { get; set; }
        public int DeliveryID { get; set; }
        public Nullable<int> InspectionID { get; set; }
        public int StatusID { get; set; }
        public bool IsArchived { get; set; }
        public bool IsUrgent { get; set; }
        public int VERSION { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DecisionID { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Inspection Inspection { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
