//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionItem
    {
        public int InspectionItemID { get; set; }
        public string Attribute { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool IsGood { get; set; }
        public Nullable<double> Measurement { get; set; }
        public Nullable<double> OrigMeasurement { get; set; }
        public Nullable<int> SampleNumber { get; set; }
        public Nullable<System.DateTime> TimeSpan { get; set; }
        public int Version { get; set; }
        public Nullable<int> CheckpointID { get; set; }
        public int InspectionID { get; set; }
        public int CavityID { get; set; }
    
        public virtual Cavity Cavity { get; set; }
        public virtual Checkpoint Checkpoint { get; set; }
        public virtual Inspection Inspection { get; set; }
    }
}
