//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.Cavities = new HashSet<Cavity>();
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
            this.InspectionItems = new HashSet<InspectionItem>();
        }
    
        public int InspectionID { get; set; }
        public decimal Humidity { get; set; }
        public int SampleSize { get; set; }
        public int NumberOfCavities { get; set; }
        public decimal Temperature { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string ControlNumber { get; set; }
        public string InspectionComments { get; set; }
        public string Comments { get; set; }
        public int VERSION { get; set; }
        public int DeliveryDetailID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EvaluatorID { get; set; }
        public bool isForReports { get; set; }
        public bool isRewrite { get; set; }
        public Nullable<int> InspectionDuration { get; set; }
        public Nullable<int> NcrID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cavity> Cavities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionItem> InspectionItems { get; set; }
        public virtual Ncr Ncr { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
