//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionInfo
    {
        public Nullable<long> InspectionId { get; set; }
        public Nullable<long> Time { get; set; }
        public string Comments { get; set; }
        public Nullable<long> DeliveryId { get; set; }
        public Nullable<long> PartId { get; set; }
        public string PartName { get; set; }
        public Nullable<long> CheckpointId { get; set; }
        public string CCode { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public string SamplingMethod { get; set; }
        public string Specification { get; set; }
        public Nullable<bool> ChIsActive { get; set; }
        public string Tool { get; set; }
        public int WithInvalid { get; set; }
    }
}
