//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Checkpoints = new HashSet<Checkpoint>();
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int PartID { get; set; }
        public string Code { get; set; }
        public System.DateTime DateMonitored { get; set; }
        public string DocNumber { get; set; }
        public bool IsMonitored { get; set; }
        public string Model { get; set; }
        public string Name { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> FileAtttachment_ID { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public bool IsSearchable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkpoint> Checkpoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual FileAttachment FileAttachment { get; set; }
    }
}
