//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
            this.Inspections = new HashSet<Inspection>();
        }
    
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public byte IsLoggedIN { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string FirstName { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public int UserID { get; set; }
        public Nullable<int> UserGroup_ID { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual UserGroupPermission UserGroupPermission { get; set; }
    }
}
