//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroupPermission()
        {
            this.Users = new HashSet<User>();
        }
    
        public int UserGroupId { get; set; }
        public byte AccessoriesPermission { get; set; }
        public byte AccountPermission { get; set; }
        public byte AlertPermission { get; set; }
        public byte DeliveryPermission { get; set; }
        public byte EvaluationPermission { get; set; }
        public byte InspectionPermission { get; set; }
        public byte MessagingPermission { get; set; }
        public string Name { get; set; }
        public byte NotificationPermission { get; set; }
        public byte PisPermission { get; set; }
        public byte ReportPermission { get; set; }
        public Nullable<int> VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
