//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsIq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Email { get; set; }
        public byte IsActive { get; set; }
        public byte IsLoggedIN { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UserGroup_ID { get; set; }
    
        public virtual UserGroupPermission UserGroupPermission { get; set; }
    }
}
